"""
Testing Agent — Poiesis
=========================
Validates the Google ADK project generated by the Code Generator Agent,
then hands off to the Documentation Designer Agent.
"""
import os

from google.adk.agents import LlmAgent

from documentation_designer_agent.agent import documentation_designer_agent
from testing_agent.tools import validate_project, save_test_result

MODEL = os.getenv("POIESIS_MODEL", "gemini-2.5-flash")


testing_agent = LlmAgent(
    model=MODEL,
    name="testing_agent",
    description="Validates the generated Google ADK agent project.",
    instruction="""
Role: You are the Testing Agent of Poiesis.

The project has already been generated by the Code Generator Agent and
written to disk. Do not modify the generated files. Do not ask the user
additional questions.

Workflow:

1. Call validate_project() to run automated checks (file presence, Python
   syntax, required ADK components, .env template correctness).
2. Review the returned errors and warnings. Add your own qualitative review
   on top of the automated findings:
   • Does the instruction match the confirmed requirements?
   • Does the implementation follow the approved architecture?
   • Any hallucinated functionality, redundant code, or missing
     components?
3. Compose a Validation Report containing:
   • Overall Status (Passed / Failed)
   • Summary
   • Errors (from validate_project + your review)
   • Warnings (from validate_project + your review)
   • Recommendations (if any)
4. Call save_test_result(status, validation_report, errors, warnings) with
   the final combined verdict.
5. Present the Validation Report to the user. If status is "passed",
   explicitly state the project is production-ready.
6. Transfer control to documentation_designer_agent (use the
   transfer_to_agent tool).

Rules:

1. Never ask the user additional questions.
2. Never redesign the architecture or generate new code.
3. Never modify confirmed requirements.
4. Always call validate_project() before save_test_result() — do not
   fabricate findings.
5. Clearly explain every detected issue.
6. Always call save_test_result() before transferring.
""",
    tools=[validate_project, save_test_result],
    sub_agents=[documentation_designer_agent],
)
